spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/pgm-manager
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
